### ISSUE TITLE
0.1.1版本无法使用Camera 1，显示error

### ISSUE THREAD

**Issue by hjf222289** [xuhao1/FOXTracker#7]
Camera 1: PS3摄像头 + CL-Eye驱动
同时0.0.8版本可正常使用，0.1.1界面截图如下。
![图片](https://user-images.githubusercontent.com/3463519/97666858-7b9b9d80-1ab9-11eb-8f71-3710bf419354.png)

**Comment by xuhao1** [comment]
After version v0.1.0, the release version is distubuted without 32bit supported since I found that 64bit version is 2x faster than 32bit. However, CL eye provide only 32bit support. So it's better to use PS3DirectShow driver instead which provide 64 bit support.
In future version, driver will be included in the application.

0.1.1以后的版本发布时使用64bit，因为效率比32bit高一倍，但是cl eye驱动只支持 32位程序。所以请使用开源的ps3directshow驱动
另外，未来的版本会直接内置ps3的驱动程序。
